


[0;36m------------------- TESTING users -------------------[0m
Service: users, App: users_app, Database: users
-------------------


[0;33mSaving data in the Python container (users) for app 'users_app'...[0m


[0;36mRunning the Django shell script inside container users...[0m
[0;31mFailed to save data for users_app in Python container users.[0m



[0;33mVerifying data in the database (users) using container (db_users)...[0m
[0;31mFailed to retrieve data for users_app in database users.[0m



[0;33mTesting connectivity to database (users) in container (db_users)...[0m
[0;32mDatabase connectivity test passed:[0m
 ?column? 
----------
        1
(1 row)




